name: GameStore Deploy

on:
  push:
    branches:
      - dev
    release:
      types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Wordpress Zip
        run: |
          WP_LINK=$(cat wp-version-control.cfg)
          wget -O "./wordpress.zip" $WP_LINK

      - name: Prepare plugins and theme zip
        run: zip -r wpcontent.zip plugins mu-plugins themes

      - name: Copy Zips to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "wordpress.zip,wpcontent.zip"
          target: ${{ github.event_name == 'push' && '/var/www/html/dev/' || '/var/www/html/live/'}}

      - name: Enable Maintenance Mode
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ".maintenance"
          target: ${{ github.event_name == 'push' && '/var/www/html/dev/' || '/var/www/html/live/'}}

      - name: Update Wordpress Core
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            find "${{ github.event_name == 'push' && '/var/www/html/dev/' || '/var/www/html/live/'}}" -type f -name "*.php" ! -name "wp-config.php" -delete
            rm -rf "${{ github.event_name == 'push' && '/var/www/html/dev/' || '/var/www/html/live/'}}/wp-admin/" "${{ github.event_name == 'push' && '/var/www/html/dev/' || '/var/www/html/live/'}}/wp-includes/"
            unzip -o "${{ github.event_name == 'push' && '/var/www/html/dev/' || '/var/www/html/live/'}}/wordpress.zip" -d "${{ github.event_name == 'push' && '/var/www/html/dev/' || '/var/www/html/live/'}}"
            mv "${{ github.event_name == 'push' && '/var/www/html/dev/' || '/var/www/html/live/'}}/wordpress/*" "${{ github.event_name == 'push' && '/var/www/html/dev/' || '/var/www/html/live/'}}/"
            rm -rf "${{ github.event_name == 'push' && '/var/www/html/dev/' || '/var/www/html/live/'}}/wordpress/"
            unzip -o "${{ github.event_name == 'push' && '/var/www/html/dev/' || '/var/www/html/live/'}}/wpcontent.zip" -d "${{ github.event_name == 'push' && '/var/www/html/dev/' || '/var/www/html/live/'}}/wp-content/"
            rm "${{ github.event_name == 'push' && '/var/www/html/dev/' || '/var/www/html/live/'}}/wordpress.zip" "${{ github.event_name == 'push' && '/var/www/html/dev/' || '/var/www/html/live/'}}/wpcontent.zip"
            chown -R www-data:www-data "${{ github.event_name == 'push' && '/var/www/html/dev/' || '/var/www/html/live/'}}"
            rm -f "${{ github.event_name == 'push' && '/var/www/html/dev/' || '/var/www/html/live/'}}/.maintenance"
            systemctl reload nginx

